### ISSUE TITLE
CRDT for tuple space?

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/jsrhoxy#2]
> It's likely that the entire tuplespace will be converted to use immutable data structures

I wonder if a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) is a good fit.

e.g. https://github.com/automerge/automerge

**Comment by JoshOrndorff** [comment]
That's an interesting concept. A quote from the linked wiki:

> much of distributed computing focuses on the problem of how to prevent concurrent updates to replicated data. But another possible approach is optimistic replication, where all concurrent updates are allowed to go through, with inconsistencies possibly created, and the results are merged or "resolved" later

At the moment I'm assuming sequential access to the rhoVM until I get the semantics good and right. But I do hope to expose a rest endpoint eventually.

**Comment by dckc** [comment]
> ... sequential access to the rhoVM ...

yes, I almost abandoned my draft of this issue when I realized the tuplespace is transactional, but CRDTs are so nifty that I just went with it. :)
